// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tollervey.LightningPayments.Breez.Services;

#nullable disable

namespace Tollervey.LightningPayments.Breez.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Tollervey.LightningPayments.Core.Models.PaymentState", b =>
                {
                    b.Property<string>("PaymentHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentHash");

                    b.ToTable("PaymentStates");
                });
#pragma warning restore 612, 618
        }
    }
}
