// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tollervey.Umbraco.LightningPayments.UI.Services;

namespace Tollervey.Umbraco.LightningPayments.UI.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20251018193314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Tollervey.LightningPayments.Core.Models.PaymentState", b =>
                {
                    b.Property<string>("PaymentHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentHash");

                    b.ToTable("PaymentStates");
                });
#pragma warning restore 612, 618
        }
    }
}
